name: sports_app
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing
version: 0.1.0

environment:
  sdk: ^3.5.0   # Compatible with Flutter 3.5 and Dart 3.5

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  cached_network_image: ^3.4.1
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  lottie: ^3.1.2
  video_player: ^2.9.1
  confetti: ^0.8.0
  google_fonts: ^6.3.2
  animated_text_kit: ^4.2.3
  icons_plus: ^5.0.0
  slider_button: ^2.1.0
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  sleek_circular_slider: ^2.1.0

dependency_overrides:
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animated_image/